/// Mirrors the `screen` values from the design prototype's state machine.
enum AppScreen {
  splash,
  welcome,
  rolePicker,
  regProperty,
  regOtp,
  regProfile,
  regPending,
  login,
  home,
  bills,
  billDetail,
  payMethod,
  paySuccess,
  complaints,
  fileComplaint,
  complaintDetail,
  notices,
  noticeDetail,
  directory,
  dirAddSelf,
  dirAddWorker,
  providerDetail,
  chat,
  visitors,
  inviteGuest,
  visitorPass,
  events,
  eventDetail,
  media,
  community,
  composePost,
  listingDetail,
  listProduct,
  myAds,
  polls,
  pollResults,
  sos,
  profile,
  settings,
  switchRole,
  notifications,
  mcDashboard,
  empDashboard,
}

/// Screens that are roots of the bottom navigation bar.
const Set<AppScreen> kRootScreens = {
  AppScreen.home,
  AppScreen.media,
  AppScreen.sos,
  AppScreen.community,
  AppScreen.polls,
  AppScreen.mcDashboard,
  AppScreen.empDashboard,
};

/// Tabs shown in the bottom nav bar (final confirmed order).
enum AppTab { polls, media, sos, community, home }
